package id.co.nds.catalogue.validators;

import java.sql.Timestamp;

import id.co.nds.catalogue.exceptions.ClientExceptions;
import id.co.nds.catalogue.exceptions.NotFoundException;

public class LoanValidator {
    public void nullCheckLoanId(String id) throws ClientExceptions {
        if(id == null) {
            throw new ClientExceptions("Loan id is required");
        }
    }

    public void notNullCheckLoanId(String id) throws ClientExceptions {
        if(id != null) {
            throw new ClientExceptions("Loan id is autogenerated, do not input id");
        }
    }

    public void nullCheckUserId(Integer userId) throws ClientExceptions {
        if(userId == null) {
            throw new ClientExceptions("User id is required");
        }
    }

    public void nullCheckUserRole(String role) throws ClientExceptions {
        if(role == null) {
            throw new ClientExceptions("Role id is required");
        }
    }

    public void nullCheckLoanAmount(Double loanAmount) throws ClientExceptions {
        if(loanAmount == null) {
            throw new ClientExceptions("Loan amount is required");
        }
    }

    public void nullCheckLoanTerm(Integer loanTerm) throws ClientExceptions {
        if(loanTerm == null) {
            throw new ClientExceptions("Loan term is required");
        }
    }

    public void nullCheckInterestRate(Double interestRate) throws ClientExceptions {
        if(interestRate == null) {
            throw new ClientExceptions("Interest rate is required");
        }
    }

    public void nullCheckCustomerName(String customerName) throws ClientExceptions {
        if(customerName == null) {
            throw new ClientExceptions("Customer name is required");
        }
    }

    public void nullCheckStartDate(Timestamp startDate) throws ClientExceptions {
        if(startDate == null) {
            throw new ClientExceptions("Start date is required");
        }
    }
    
    public void nullCheckObject(Object o) throws NotFoundException {
        if(o == null) {
            throw new NotFoundException("Loan details not found");
        }
    }

    public void validateLoanId(String id) throws ClientExceptions{
        if(id.length() != 10 || !id.startsWith("L")) {
            throw new ClientExceptions("Loan id must contains 10 digits and starts with 'L'");
        }
    }

    public void validateUserId(Integer userId) throws ClientExceptions{
        if(userId <= 0) {
            throw new ClientExceptions("User Id is required");
        }
    }

    public void validateRoleId(String roleId) throws ClientExceptions{
        if(roleId.length() != 5 || !roleId.startsWith("R")) {
            throw new ClientExceptions("Role id must contains five digits and starts with 'R'");
        }
    }

    public void validateLoanAmount(Double loanAmount) throws ClientExceptions {
        if(loanAmount < 0) {
            throw new ClientExceptions("Loan amount must be positive integer number");
        }
    }

    public void validateLoanTerm(Integer loanTerm) throws ClientExceptions {
        if(loanTerm < 0) {
            throw new ClientExceptions("Loan term must be positive integer number");
        }
    }

    public void validateInterestRate(Double interestRate) throws ClientExceptions {
        if(interestRate < 0) {
            throw new ClientExceptions("Interest rate must be positive integer number");
        }
    }

    public void validateCustomerName(String customerName) throws ClientExceptions {
        if(customerName.trim().equalsIgnoreCase("")) {
            throw new ClientExceptions("Customer name is required");
        }
    }

    public void validateStartDate(Timestamp startDate) throws ClientExceptions {
        if(startDate == null) {
            throw new ClientExceptions("Start date is required");
        }
    }
}
