package id.co.nds.catalogue.validators;

import id.co.nds.catalogue.exceptions.ClientExceptions;
import id.co.nds.catalogue.exceptions.NotFoundException;
import id.co.nds.catalogue.globals.GlobalConstant;

public class UserValidator {
    public void nullCheckUserId(Integer id) throws ClientExceptions {
        if(id == null) {
            throw new ClientExceptions("User id is required");
        }
    }
       public void notNullCheckUserId(Integer id) throws ClientExceptions {
        if(id != null) {
            throw new ClientExceptions("User id is autogenerated, do not input id");
        }
    }

    public void nullCheckFullname(String fullname) throws ClientExceptions {
        if(fullname == null) {
            throw new ClientExceptions("Fullname is required");
        }
    }

    public void nullCheckRoleId(String roleId) throws ClientExceptions {
        if(roleId == null) {
            throw new ClientExceptions("Role id is required");
        }
    }

    public void nullCheckCallNumber(String callNumber) throws ClientExceptions {
        if(callNumber == null) {
            throw new ClientExceptions("Call number is required");
        }
    }
    
    public void nullCheckObject(Object o) throws NotFoundException {
        if(o == null) {
            throw new NotFoundException("User is not found");
        }
    }

    public void validateUserId(Integer id) throws ClientExceptions {
        if(id <= 0) {
            throw new ClientExceptions("User id input is invalid");
        }
    }

    public void validateFullname(String fullname) throws ClientExceptions {
        if(fullname.trim().equalsIgnoreCase("")) {
            throw new ClientExceptions("Fullname is required");
        }
    }

    public void validateCheckRolelId(String roleId) throws ClientExceptions {
        if(roleId.length() != 5 && !roleId.startsWith("R")) {
            throw new ClientExceptions("Role id must be 5 digits and starts with 'R'");
        }
    }

    public void validateCallNumber(String callNumber) throws ClientExceptions {
        if(!callNumber.startsWith("0") && callNumber.length() < 9 || callNumber.length() > 12) {
            throw new ClientExceptions("Call number must starts with '0' and have 9 - 12 digits");
        }
        else if(!callNumber.startsWith("+62") && callNumber.length() < 11 || callNumber.length() > 14) {
            throw new ClientExceptions("Call number must starts with '+62' and have 11 - 14 digits");
        }
    }

    public void validateRecStatus(String id, String recStatus) throws ClientExceptions {
        if(recStatus.equalsIgnoreCase(GlobalConstant.REC_STATUS_NONACTIVE)) {
            throw new ClientExceptions("User with id - " + id + " is already been deleted.");
        }
    }
}
